# Site settings
title: "About Aarya"
description: "Computational Biologist at the University of Georgia"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Aarya Venkat"
resume_title:                   "Computational Biologist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "https://docs.google.com/viewer?url=https://github.com/arikat/Arikat-Additional-Files/raw/master/Aarya_CV.pdf"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "678-404-1666"
#resume_contact_address:         ""

resume_header_contact_info:     "678-404-1666 • aarya@uga.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>Data scientist with a background in protein engineering and computational glycobiology. Skilled in Molecular Dynamics (MD) simulations, molecular modeling, bio/cheminformatics, and deep learning.</p>"

resume_looking_for_work:        "yes"

# Decide which sections to use
#resume_section_experience:      true
#resume_section_education:       true
#resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

resume_social_links:
  resume_github_url:            "https://github.com/arikat"
  resume_linkedin_url:          "https://www.linkedin.com/in/aaryavenkat"
  resume_website_url:           "https://mstdn.social/@aarya"
  resume_medium_url:            "https://aarya.medium.com/"
  resume_instagram_url:         "https://arikat.github.io/art"
 # resume_mastodon_url:          "https://mstdn.social/@aarya"


resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-tactile
